# zal edit workload to test io on linux raid, used together with `properties/raid.properties`

# data size: 4GB = 1GB load + 3GB transaction

recordcount=1048576

operationcount=3145728
insertproportion=0.79
readproportion=0.15
updateproportion=0.05
scanproportion=0
deleteproportion=0.01

workload=zal.test.io.ssd

requestdistribution=zipfian


# zal add to control key&value length
## zeropadding should - 4 because there is a prefix "user" in every key
# key_len: 24 Bytes
zeropadding=20

## in order to have value length==1000, valuelength = (fieldlength + 14) * fieldcount
# BUG yet to figer out what `14` is
# value_len: 1000 Bytes
fieldlength=986
fieldcount=1